import {
  ACCENT_SWATCHES,
  CATEGORY_LABELS,
  NODE_CATEGORIES,
  NODE_LIBRARY,
  TECH_CATALOG,
} from "./node-types";

export function diagramAgentInstructions(): string {
  const types = NODE_CATEGORIES.map((category) => {
    const items = NODE_LIBRARY.filter((item) => item.category === category)
      .map((item) => `${item.id} (${item.label}, default scope ${item.defaultScope})`)
      .join(", ");
    return `${CATEGORY_LABELS[category]}: ${items}`;
  }).join("\n");
  const technologies = TECH_CATALOG.map((item) => item.id).join(", ");
  const accents = ACCENT_SWATCHES.join(", ");

  return [
    "ClusterDeck is an infrastructure diagram editor. Each diagram is a canvas of nodes and edges.",
    "Workflow (like n8n node docs): list_diagrams → get_diagram → update_diagram. Always read before large edits.",
    "MCP access is off per project until enabled. Enabling a project opens its root and every inner diagram. list_diagrams returns only those.",
    "Use only listed type ids, technology ids, shapes, and accent swatches.",
    "",
    "## Tools",
    "- list_diagrams: find diagram ids (optional query).",
    "- get_diagram: full snapshot { nodes, edges, meta }. Use node ids from here when updating.",
    "- update_diagram: upsert/delete nodes and edges; optional meta. Omitted fields on an existing id are kept. Arrays you send (tags, technologies, properties, connectors, tagDefs, flows) replace the previous array.",
    "",
    "## Node frame (all kinds)",
    "id?, kind?, position {x,y}, parentId (null to detach), width?, height?.",
    "A new node needs position. Omit id to create one.",
    "Children of a group use parentId and positions relative to the group's top-left.",
    "",
    "## kind: infra (component card)",
    "Requires typeId on create. Fields:",
    "- title, subtitle, description (markdown), displayDescription (short canvas caption)",
    "- tags: string[], technologies: tech ids from the catalog",
    "- status: healthy|degraded|unknown|offline",
    "- shape: rounded|rectangle|cylinder|hexagon|actor|stadium",
    "- scope: internal|external (external = dashed outline)",
    "- lifecycle: live|future|deprecated|removed (future = dashed outline)",
    "- accentColor: hex from the swatch list, or null to reset to type default",
    "- properties: key/value rows shown in the inspector and optionally on the canvas",
    "- connectors: publish inner-diagram nodes as extra in/out handles on THIS parent card",
    "childDiagramId / childCount are system-managed when a user opens an inner diagram; do not invent childDiagramId.",
    "",
    "### properties (canvas facts)",
    "Array of { key, value, icon?, showOnCanvas?, id? }.",
    "- key/value: e.g. key \"OS\", value \"Windows\" or \"Linux\"; key \"IP\", value \"10.10.52.69\".",
    "- showOnCanvas: default true. Set false to keep the fact only in the inspector.",
    "- icon: optional Iconify id string (e.g. \"mdi:microsoft-windows\", \"mdi:linux\", \"mdi:ip-network\").",
    "- Sending properties replaces the whole list. To clear, send [].",
    "",
    "### connectors (parent publish points)",
    "Only meaningful on infra/group nodes that have an inner diagram.",
    "Array of { nodeId, title, direction } where direction is \"in\"|\"out\".",
    "- nodeId: id of a node INSIDE the child diagram (from get_diagram on that child).",
    "- title: label shown next to the handle on the parent (usually the inner node title).",
    "- Edge handles use ids \"in:<nodeId>\" and \"out:<nodeId>\". Set edge sourceHandle/targetHandle to those when wiring to a published connector.",
    "- Sending connectors replaces the whole list. To clear, send [].",
    "",
    "## kind: group (subworkflow frame)",
    "Fields: title, subtitle, description (markdown), tags, connectors (same publish rules as infra).",
    "",
    "## kind: note",
    "Fields: title, body, tone (text|comment).",
    "",
    "## kind: port",
    "Inherited link stubs. Fields: title, direction (in|out), protocol, parentNodeId, parentEdgeId.",
    "",
    "## Edges",
    "Fields: id?, source, target, label?, reverseLabel?, animated?, lineShape (bezier|straight|step),",
    "direction (forward|backward|both, default forward), sourceHandle?, targetHandle?.",
    "Handles: omit or null for the default side handle; use \"in:<id>\" / \"out:<id>\" for published connectors.",
    "Prefer direction both + reverseLabel for bidirectional traffic on one edge.",
    "Two edges between the same nodes are drawn as separate arcs.",
    "Deletes: deleteNodeIds / deleteEdgeIds. Edges with missing endpoints are dropped automatically.",
    "",
    "## meta (diagram-level)",
    "Optional on update_diagram: { tagDefs?, flows? }.",
    "- tagDefs: [{ id, label, color }] colors for tag chips / perspectives.",
    "- flows: [{ id, name, color, edgeIds[] }] named paths that highlight edges.",
    "Each field you send replaces that array entirely.",
    "",
    "## Infra type ids",
    types,
    "",
    `Technology ids: ${technologies}`,
    "",
    `Accent swatches: ${accents}`,
    "",
    "## Examples",
    "Set OS on a node:",
    '{ "diagramId": "…", "upsertNodes": [{ "id": "factory-server", "properties": [{ "key": "OS", "value": "Linux", "icon": "mdi:linux", "showOnCanvas": true }, { "key": "IP", "value": "10.10.52.69", "showOnCanvas": true }] }] }',
    "",
    "Publish inner Service as In/Out on parent App:",
    '{ "diagramId": "<parent>", "upsertNodes": [{ "id": "<parentNode>", "connectors": [{ "nodeId": "<innerServiceId>", "title": "Service", "direction": "in" }, { "nodeId": "<innerServiceId>", "title": "Service", "direction": "out" }] }] }',
    "",
    "Wire an edge into a published connector:",
    '{ "upsertEdges": [{ "source": "gateway", "target": "app", "targetHandle": "in:<innerServiceId>", "label": "HTTPS" }] }',
  ].join("\n");
}
