import {
  Activity,
  Archive,
  Bell,
  Box,
  Clock,
  Cloud,
  Cog,
  Database,
  FileCode,
  Fingerprint,
  GitFork,
  Globe,
  HardDrive,
  Inbox,
  Key,
  Layers,
  ListOrdered,
  Puzzle,
  Radio,
  ScrollText,
  Search,
  Shapes,
  Shield,
  Table2,
  User,
  Zap,
  type LucideIcon,
} from "lucide-react";
import type { InfraNodeTypeId } from "@dataflow/shared";

export const NODE_ICONS: Record<InfraNodeTypeId, LucideIcon> = {
  service: Shield,
  lambda: Zap,
  container: Box,
  worker: Cog,
  cron: Clock,
  postgres: Database,
  redis: Layers,
  s3: HardDrive,
  storage: Archive,
  search: Search,
  table: Table2,
  custom: Shapes,
  kafka: Radio,
  rabbitmq: Inbox,
  queue: ListOrdered,
  "load-balancer": GitFork,
  "api-gateway": Globe,
  cdn: Cloud,
  "third-party": Puzzle,
  user: User,
  auth: Fingerprint,
  logs: ScrollText,
  metrics: Activity,
  alerts: Bell,
  "config-map": FileCode,
  secret: Key,
};

export const TECH_ICONS: Record<string, LucideIcon> = {
  box: Box,
  zap: Zap,
  "file-code": FileCode,
  database: Database,
  layers: Layers,
  radio: Radio,
  "hard-drive": HardDrive,
  "git-fork": GitFork,
  globe: Globe,
  cloud: Cloud,
  puzzle: Puzzle,
  activity: Activity,
  archive: Archive,
  bell: Bell,
  cog: Cog,
  inbox: Inbox,
  search: Search,
  "scroll-text": ScrollText,
};
