export type PropertyPreset = {
  key: string;
  icon: string;
  value?: string;
};

export const PROPERTY_PRESETS: PropertyPreset[] = [
  { key: "Server", icon: "lucide:server" },
  { key: "Host", icon: "lucide:network" },
  { key: "Port", icon: "lucide:plug" },
  { key: "Runtime", icon: "mdi:docker" },
];

export const POPULAR_PROPERTY_ICONS: string[] = [
  "lucide:server",
  "lucide:network",
  "lucide:plug",
  "lucide:globe",
  "lucide:database",
  "lucide:cloud",
  "lucide:box",
  "lucide:package",
  "lucide:container",
  "lucide:cpu",
  "lucide:memory-stick",
  "lucide:hard-drive",
  "lucide:disc",
  "lucide:key-round",
  "lucide:lock",
  "lucide:unlock",
  "lucide:shield",
  "lucide:shield-check",
  "lucide:user-round",
  "lucide:users",
  "lucide:mail",
  "lucide:message-square",
  "lucide:phone",
  "lucide:git-branch",
  "lucide:git-commit-horizontal",
  "lucide:git-merge",
  "lucide:terminal",
  "lucide:code",
  "lucide:code-xml",
  "lucide:file-code",
  "lucide:folder",
  "lucide:settings",
  "lucide:wrench",
  "lucide:sliders-horizontal",
  "lucide:activity",
  "lucide:gauge",
  "lucide:radar",
  "lucide:bell",
  "lucide:clock",
  "lucide:timer",
  "lucide:calendar",
  "lucide:map-pin",
  "lucide:route",
  "lucide:link",
  "lucide:unplug",
  "lucide:wifi",
  "lucide:radio",
  "lucide:antenna",
  "lucide:layers",
  "lucide:layout-grid",
  "lucide:workflow",
  "lucide:binary",
  "lucide:braces",
  "lucide:hash",
  "lucide:tag",
  "lucide:tags",
  "lucide:bookmark",
  "lucide:star",
  "lucide:heart",
  "lucide:zap",
  "lucide:flame",
  "lucide:rocket",
  "lucide:bot",
  "lucide:brain",
  "lucide:eye",
  "lucide:search",
  "lucide:filter",
  "lucide:upload",
  "lucide:download",
  "lucide:refresh-cw",
  "lucide:repeat",
  "lucide:play",
  "lucide:pause",
  "lucide:circle-stop",
  "lucide:power",
  "lucide:monitor",
  "lucide:smartphone",
  "lucide:tablet",
  "lucide:laptop",
  "mdi:docker",
  "mdi:kubernetes",
  "mdi:nginx",
  "mdi:apache",
  "mdi:aws",
  "mdi:google-cloud",
  "mdi:microsoft-azure",
  "mdi:server",
  "mdi:server-network",
  "mdi:database",
  "mdi:database-outline",
  "mdi:ip-network",
  "mdi:ip",
  "mdi:port",
  "mdi:lan",
  "mdi:lan-connect",
  "mdi:api",
  "mdi:api-off",
  "mdi:cloud-outline",
  "mdi:cloud-sync",
  "mdi:cloud-check",
  "mdi:firewall",
  "mdi:vpn",
  "mdi:key-variant",
  "mdi:certificate",
  "mdi:security",
  "mdi:shield-lock",
  "mdi:account-key",
  "mdi:console",
  "mdi:bash",
  "mdi:powershell",
  "mdi:docker",
  "mdi:cube-outline",
  "mdi:package-variant",
  "mdi:memory",
  "mdi:chip",
  "mdi:harddisk",
  "mdi:nas",
  "mdi:router-wireless",
  "mdi:access-point",
  "mdi:rabbit",
  "mdi:elephant",
  "mdi:leaf",
  "mdi:graphql",
  "mdi:websocket",
  "mdi:webhook",
  "mdi:timer-outline",
  "mdi:clock-outline",
  "mdi:pulse",
  "mdi:chart-line",
  "mdi:chart-bar",
  "mdi:bug",
  "mdi:test-tube",
  "mdi:cog-outline",
  "mdi:toolbox-outline",
  "simple-icons:github",
  "simple-icons:gitlab",
  "simple-icons:bitbucket",
  "simple-icons:docker",
  "simple-icons:kubernetes",
  "simple-icons:nginx",
  "simple-icons:redis",
  "simple-icons:postgresql",
  "simple-icons:mysql",
  "simple-icons:mongodb",
  "simple-icons:elasticsearch",
  "simple-icons:apachekafka",
  "simple-icons:rabbitmq",
  "simple-icons:prometheus",
  "simple-icons:grafana",
  "simple-icons:elasticsearch",
  "simple-icons:nginx",
  "simple-icons:cloudflare",
  "simple-icons:amazonaws",
  "simple-icons:googlecloud",
  "simple-icons:microsoftazure",
  "simple-icons:digitalocean",
  "simple-icons:terraform",
  "simple-icons:ansible",
  "simple-icons:jenkins",
  "simple-icons:githubactions",
  "simple-icons:argo",
  "simple-icons:helm",
  "simple-icons:istio",
  "simple-icons:envoyproxy",
  "simple-icons:nginx",
  "simple-icons:traefikproxy",
  "simple-icons:hashicorp",
  "simple-icons:vault",
  "simple-icons:consul",
  "simple-icons:nomad",
  "simple-icons:nodejs",
  "simple-icons:python",
  "simple-icons:go",
  "simple-icons:rust",
  "simple-icons:typescript",
  "simple-icons:react",
  "simple-icons:nextdotjs",
  "simple-icons:nestjs",
  "simple-icons:fastapi",
  "simple-icons:spring",
  "simple-icons:dotnet",
  "simple-icons:graphql",
  "simple-icons:grpc",
  "simple-icons:openapiinitiative",
  "simple-icons:swagger",
  "simple-icons:sentry",
  "simple-icons:datadog",
  "simple-icons:newrelic",
  "simple-icons:opentelemetry",
  "simple-icons:jaeger",
  "simple-icons:clickhouse",
  "simple-icons:apachecassandra",
  "simple-icons:scylladb",
  "simple-icons:sqlite",
  "simple-icons:mariadb",
  "simple-icons:supabase",
  "simple-icons:firebase",
  "simple-icons:auth0",
  "simple-icons:okta",
  "simple-icons:keycloak",
];

export function iconLabel(icon: string): string {
  const [, name = icon] = icon.split(":");
  return name.replace(/[-_]/g, " ");
}

export function uniqueIcons(icons: string[]): string[] {
  return [...new Set(icons)];
}

export function filterPopularIcons(query: string): string[] {
  const normalized = query.trim().toLowerCase();
  const all = uniqueIcons(POPULAR_PROPERTY_ICONS);
  if (!normalized) return all;
  return all.filter((icon) => icon.toLowerCase().includes(normalized));
}

export async function searchIconifyIcons(query: string, limit = 120): Promise<string[]> {
  const normalized = query.trim();
  if (!normalized) return filterPopularIcons("").slice(0, limit);

  const local = filterPopularIcons(normalized);
  try {
    const response = await fetch(
      `https://api.iconify.design/search?query=${encodeURIComponent(normalized)}&limit=${limit}`,
    );
    if (!response.ok) return local.slice(0, limit);
    const payload = (await response.json()) as { icons?: string[] };
    return uniqueIcons([...local, ...(payload.icons ?? [])]).slice(0, limit);
  } catch {
    return local.slice(0, limit);
  }
}
